### ISSUE TITLE
[Improvement] Add proper styling to the web page.

### ISSUE THREAD

**Issue by rohitbutbliss** [codomen4community/contests-finder#1]
As I am just starting out & this is the first version of our application. I haven't provided proper styling yet.

I would also appreciate if someone wants to contribute to the styling.

Thanks.

**Comment by Osauyi** [comment]
>I would also appreciate if someone wants to contribute to the styling.
is  there no design from you in mind?

**Comment by rohitbutbliss** [comment]
Tbh, when I pushed this project it was late at night so I didn't plan any specific design. I will be working on design as well once I get time. But if you have any design in mind please do share it, we can probably make it work 😊.

P.S : Last line doesn't have anything to do with my poor designing skills 🥹

**Comment by Osauyi** [comment]
>But if you have any design in mind please do share it, we can probably make it work 😊.

I'm a beginner, you can show me a reference and I can use that but.........i got the same problem with you  :  - \

**Comment by rohitbutbliss** [comment]
Alright @Osauyi, I will be creating some reference designs & post it here soon 🤞🏻.

**Comment by Osauyi** [comment]
Thank you : -)

**Comment by rohitbutbliss** [comment]
Hi @Osauyi, we have made some changes in styling of the page. You can check them out in the recent two commits as well as on the deployed link as well.

- Additionally, we have planned to change the styling of the each contest card. Right now, we have created a basic sketch which look like this :

<img width="1370" alt="Screenshot 2023-03-13 at 10 38 10 PM" src="https://user-images.githubusercontent.com/84085728/224775895-acf31d71-a574-479f-b254-504478346189.png">

- We have decided that we will be merging date & time together, format will be [DD/MM/YYYY,HH:MM]

You can start working on styling of cards according to the sketch mentioned above. Right now, you can use dummy images but we will be adding current images soon.

**Comment by Osauyi** [comment]
Aright

**Comment by Osauyi** [comment]
Woah it's harder than i thought i can configure the JavaScript right? Only the part where you created the div

**Comment by Osauyi** [comment]
![Screenshot 2023-03-14 at 11-22-00 Contest Viewer By Rohit](https://user-images.githubusercontent.com/77385035/224970980-29db4af0-1e72-47a0-a4be-4cc93cf2bff8.png)


something like this???

**Comment by rohitbutbliss** [comment]
Yes, you can configure javascript for adding images to contests. But for rest of the things, I would suggest to confugure css file only.

> Woah it's harder than i thought i can configure the JavaScript right? Only the part where you created the div

**Comment by Osauyi** [comment]
>We have decided that we will be merging date & time together, format will be [DD/MM/YYYY,HH:MM]

what about this?

**Comment by rohitbutbliss** [comment]
Yep you are going in right direction. Since, we will be merging date & time so card height will also reduce. We want to set image height equals to card height(except padding). And rest of the information should fit in the same so we need to play around with font sizes as well on smaller screens. Would prefer to use variables in root selector for font size so that it will easier for us to keep font sizes in check.

> ![Screenshot 2023-03-14 at 11-22-00 Contest Viewer By Rohit](https://user-images.githubusercontent.com/77385035/224970980-29db4af0-1e72-47a0-a4be-4cc93cf2bff8.png)
> 
> something like this???

**Comment by rohitbutbliss** [comment]
Ahh yes, my bad I forgot about it, you can configure js for merging date & time.

> > We have decided that we will be merging date & time together, format will be [DD/MM/YYYY,HH:MM]
> 
> what about this?

**Comment by Osauyi** [comment]
>Yes, you can configure javascript for adding images to contests. But for rest of the things, I would suggest to confugure css file only.

i created two separate div with JavaScript to append the card to one and the other with the background image of the logo so the display flex would work.......

i don't know another way

**Comment by rohitbutbliss** [comment]
Yep, looks fine to me but we need to keep data in check. As long as it is not causing issue with the data shown. It will be fine for us.

> > Yes, you can configure javascript for adding images to contests. But for rest of the things, I would suggest to confugure css file only.
> 
> i created two separate div with JavaScript to append the card to one and the other with the background image of the logo so the display flex would work.......
> 
> i don't know another way

**Comment by Osauyi** [comment]
In the sketch you gave me am i leaving the site name or removing it?

**Comment by rohitbutbliss** [comment]
Since, we will be adding logo of the site instead so we are planning to remove site name. It is not final yet so you can leave it as it is for now.

> In the sketch you gave me am i leaving the site name or removing it?

**Comment by Osauyi** [comment]
![image](https://user-images.githubusercontent.com/77385035/224978839-e81e6c2b-f24c-4518-a87b-85f8ab1582d8.png)

this it?

![image](https://user-images.githubusercontent.com/77385035/224980076-2f1d3826-e1b9-4c23-9b50-efbb7cfcf946.png)

desktop version

**Comment by rohitbutbliss** [comment]
Mobile version looks good. As for Desktop version  I wanted to ask if you are using display: flex & wrap property or are you using grid? I would prefer grid otherwise wrap property might look different on different screens sizes. Otherwise they are looking really good to me.

**Comment by Osauyi** [comment]
> Mobile version looks good. As for Desktop version I wanted to ask if you are using display: flex & wrap property or are you using grid? I would prefer grid otherwise wrap property might look different on different screens sizes. Otherwise they are looking really good to me.

using grid, the project name is taking the 2 colunms

**Comment by Osauyi** [comment]
![image](https://user-images.githubusercontent.com/77385035/225003257-c86df6ce-ecf2-470e-9d25-aa107267dcce.png)

some of the blocks got this issue? is it the api?

**Comment by rohitbutbliss** [comment]
Hmm, I don't think it should be the issue, can you please share the code(preferably github) with me.

**Comment by rohitbutbliss** [comment]
As I can see that it is showing me correct data for the same constest on current master version.

![Screenshot_20230314_182644_Chrome](https://user-images.githubusercontent.com/84085728/225007948-cd9a8dc4-2f9b-4140-b023-545e9f116f3d.jpg)

There must be some issue with the code.

**Comment by rohitbutbliss** [comment]
Nice work man 👏 Let us fix this NaN issue & create a pull request if everything goes well.

> > Mobile version looks good. As for Desktop version I wanted to ask if you are using display: flex & wrap property or are you using grid? I would prefer grid otherwise wrap property might look different on different screens sizes. Otherwise they are looking really good to me.
> 
> using grid, the project name is taking the 2 colunms

**Comment by Osauyi** [comment]
contestDiv.append(currentContestDiv);

    const gate = 
      document.createElement("div")
      // gate.innerHtml = "sup"
      // gate.style.height = "300px"
      // gate.style.backgroundColor = "red";
      gate.classList.add("addImage")


    currentContestDiv.appendChild(gate)
    const nake = 
      document.createElement("div")
      // nake.innerHtml = "sup"
      // nake.style.height = "300px"
      // nake.style.backgroundColor = "red";
          nake.append(currentAnchorTag);
    nake.append(currentSite);
    nake.append(startDate);
    nake.append(endDate);
    // nake.append(startTime);
    // nake.append(endTime);
    nake.append(duration);

      nake.classList.add("cardDetails")


    currentContestDiv.appendChild(nake)``

**Comment by Osauyi** [comment]
startDate.textContent = `Start Date : ${start_date.getDate()}/${
      start_date.getMonth() + 1
    }/${start_date.getFullYear()}, ${start_date.getHours()}:${start_date.getMinutes()}`;
    endDate.textContent = `End Date : ${end_date.getDate()}/${
      end_date.getMonth() + 1
    }/${end_date.getFullYear()},  ${end_date.getHours()}:${end_date.getMinutes()}`;
    // startTime.textContent = `Start Time : ${start_date.getHours()}:${start_date.getMinutes()}`;
    // endTime.textContent = `End Time : ${end_date.getHours()}:${end_date.getMinutes()}`;
    duration.textContent = `Duration : ${durationSimplifier(contest.duration)}`;``

**Comment by rohitbutbliss** [comment]
Could you please check what are the values stored in start_date & end_date once?

**Comment by rohitbutbliss** [comment]
Also, I would appreciate it if you can push your current code in your fork. It will be helpful to debug it.

**Comment by Osauyi** [comment]
>Also, I would appreciate it if you can push your current code in your fork. It will be helpful to debug it.

I've commit those code to the branch

**Comment by Osauyi** [comment]
>Could you please check what are the values stored in start_date & end_date once?

yeahhh. don't understand, did you mean console.log??

**Comment by rohitbutbliss** [comment]
I was asking to check values stored in start_date & end_date are in the form of Date() only but they seem fine to me. Is the issue still there? I will check the the issue with the code in some time.

> > Could you please check what are the values stored in start_date & end_date once?
> 
> yeahhh. don't understand, did you mean console.log??

**Comment by Osauyi** [comment]
> I was asking to check values stored in start_date & end_date are in the form of Date() only but they seem fine to me. Is the issue still there? I will check the the issue with the code in some time.
> 
> > > Could you please check what are the values stored in start_date & end_date once?
> > 
> > 
> > yeahhh. don't understand, did you mean console.log??

Yep 
I'll try to trace my steps whether the error was from me

**Comment by Osauyi** [comment]
> > I was asking to check values stored in start_date & end_date are in the form of Date() only but they seem fine to me. Is the issue still there? I will check the the issue with the code in some time.
> > > > Could you please check what are the values stored in start_date & end_date once?
> > > 
> > > 
> > > yeahhh. don't understand, did you mean console.log??
> 
> Yep I'll try to trace my steps whether the error was from me

Just checked it, it seems the error was from your main code or something i copied the script created new branch but its still showing the same thing. Try from your end

**Comment by rohitbutbliss** [comment]
Apparently, your code is working fine on my device, can you please hard reload or change the browser to check if it is working fine or not. It looks like the issue is not from code.

<img width="1440" alt="Screenshot 2023-03-14 at 8 22 32 PM" src="https://user-images.githubusercontent.com/84085728/225040583-b79631a7-3603-43fe-85e2-f4d07a7dc4f0.png">



> > > I was asking to check values stored in start_date & end_date are in the form of Date() only but they seem fine to me. Is the issue still there? I will check the the issue with the code in some time.
> > > > > Could you please check what are the values stored in start_date & end_date once?
> > > > 
> > > > 
> > > > yeahhh. don't understand, did you mean console.log??
> > 
> > 
> > Yep I'll try to trace my steps whether the error was from me
> 
> Just checked it, it seems the error was from your main code or something i copied the script created new branch but its still showing the same thing. Try from your end

**Comment by Osauyi** [comment]
yep I change the browser  and there was no issues...

so are we good to go?

**Comment by rohitbutbliss** [comment]
Sure, you can create a pull request now 😉

**Comment by rohitbutbliss** [comment]
Thank you for your contribution. I have merged your pull request 🥳
